export const weatherMap = {
  0: { desc: "Cielo sereno", icon: "01d" },
  1: { desc: "Prevalentemente sereno", icon: "02d" },
  2: { desc: "Parzialmente nuvoloso", icon: "03d" },
  3: { desc: "Coperto", icon: "04d" },
  45: { desc: "Nebbia", icon: "50d" },
  48: { desc: "Nebbia con brina", icon: "50d" },
  51: { desc: "Pioggerella leggera", icon: "09d" },
  53: { desc: "Pioggerella moderata", icon: "09d" },
  55: { desc: "Pioggerella intensa", icon: "09d" },
  61: { desc: "Pioggia leggera", icon: "10d" },
  63: { desc: "Pioggia moderata", icon: "10d" },
  65: { desc: "Pioggia intensa", icon: "10d" },
  80: { desc: "Rovesci leggeri", icon: "09d" },
  81: { desc: "Rovesci moderati", icon: "09d" },
  82: { desc: "Rovesci forti", icon: "09d" },
  95: { desc: "Temporale", icon: "11d" },
  96: { desc: "Temporale con grandine", icon: "11d" },
  99: { desc: "Temporale violento", icon: "11d" },
};
